#server:
#  port: 8761
#spring:
#  profiles:
#    active: peer1
#  application:
#    name: Eureka-Server-1
  #官方写的就是 8761
#security:
#  basic:
#    enabled: true #启用安全处理
#  user:
#    name: admin
#    password: 123456
#spring:
#  profiles: peer1
server:
  port: 8761
eureka:
  instance:                   #定义Eureka实例
    hostname: eureka-7001.com #Eureka实例所在的主机名

  #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:8761/eureka




