server:
  port: 7001

#security:
#  basic:
#    enabled: true #启用安全处理
#  user:
#    name: admin
#    password: 123456

eureka:
  instance:                   #定义Eureka实例
    hostname: eureka-7001.com #Eureka实例所在的主机名

  #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true
    server:
      eviction-interval-timer-in-ms: 6000 #设置清理的间隔时间(默认6000ms)
      enable-self-preservation: false #关闭保护模式